### ISSUE TITLE
Create "user" table

### ISSUE THREAD

**Issue by reenatoteixeira** [reenatoteixeira/just-another-todo-list#43]
To be able to register new users and allow users to login, there's the need to create a "users" table in the database.

The table must have the following fields:
- id, INT, NOT NULL, AUTO INCREMENT, PRIMARY KEY
- first_name, VARCHAR(100), NOT NULL
- last_name, VARCHAR(100), NOT NULL
- email, VARCHAR(100), NOT NULL
- password, VARCHAR(200), NOT NULL
- token, VARCHAR(200), NOT NULL

**Comment by TillTHMAcc** [comment]
Can I and a student colleague create your database?

**Comment by reenatoteixeira** [comment]
hey! what's up?

I already have the database, just need to add this new "user" table.
You and your colleague can run the project if you guys want to, and create the database from scratch too 😄

Feel free to contact me if you need any help
________________________________

**Comment by reenatoteixeira** [comment]
Table created:
![Image](https://github.com/reenatoteixeira/just-another-todo-list/assets/99664161/2020ed18-08c3-4c7b-98a9-ee60501075e0)
